push-external:
  stage: transfer-external
  tags: 
    - powershell
    - unity
    - windows-runner-01
  when: manual
  only: 
    - develop-art
  allow_failure: true
  script:
    - git lfs fetch origin --all
    # Check existing remotes
    - echo "Existing remotes:"
    - git remote -v

    # Optional: Verify the correct remote is defined
    - |
      if (git remote get-url $EXTERNAL_REMOTE) {
        Write-Host "Remote $EXTERNAL_REMOTE already exists."
      } else {
        Write-Host "Adding remote $EXTERNAL_REMOTE..."
        git remote add $EXTERNAL_REMOTE https://$EXTERNAL_ACCESS_TOKEN@$EXTERNAL_REMOTE_PATH
      }

    # Push all tags to the existing remote
    - Write-Host "Pushing to the remote repository..."
    - git push $EXTERNAL_REMOTE HEAD:refs/heads/$CI_COMMIT_BRANCH
    - git lfs push --all $EXTERNAL_REMOTE

pull-external:
  stage: transfer-external
  when: manual
  only: 
    - develop-art
  tags: 
    - powershell
    - unity
    - windows-runner-01
  allow_failure: true
  script:
    # Check existing remotes
    - echo "Existing remotes:"
    - git remote -v

    # Optional: Verify the correct remote is defined
    # - |
    #   if (git remote get-url $INTERNAL_REMOTE) {
    #     Write-Host "Remote $INTERNAL_REMOTE already exists."
    #   } else {
    #     Write-Host "Adding remote $EXTERNAL_REMOTE..."
    #     git remote add $INTERNAL_REMOTE http://$INTERNAL_ACCESS_TOKEN@$INTERNAL_REMOTE_PATH
    #   }

    # pull from external remote
    - Write-Host "Pulling from the remote repository..."
    # - git pull $EXTERNAL_REMOTE develop
    # - git lfs fetch --all $EXTERNAL_REMOTE
    # - git push $INTERNAL_REMOTE HEAD:refs/heads/develop
    # - git lfs push --all $INTERNAL_REMOTE
    - git remote add $EXTERNAL_REMOTE https://$EXTERNAL_ACCESS_TOKEN@$EXTERNAL_REMOTE_PATH.git
    - git lfs fetch $EXTERNAL_REMOTE --all
    - git pull $EXTERNAL_REMOTE $CI_COMMIT_BRANCH
    - git remote add $INTERNAL_REMOTE http://$INTERNAL_REMOTE_USER:$INTERNAL_ACCESS_TOKEN@$INTERNAL_REMOTE_PATH.git
    - git push -u $INTERNAL_REMOTE $CI_COMMIT_BRANCH